baseURL                    = "https://jr3n.github.io/"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "B.Y.O.B"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"
  work-note                = "work-note/:year-:month/:slug/"

[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"

  [[menu.main]]
    name                   = "Work-note"
    weight                 = -110
    identifier             = "work-note"
    url                    = "work-note/"

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"

[params]
  faviconfile              = "img/favicon.ico"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Renato"
  description              = ["Keep learning.", "Think like a hacker.", "與其取悅這個世界的法則，倒不如造就理想的自己"]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "zx1zx2jr3n@gmail.com"
  github                   = "https://github.com/Jr3n/"
  #linkedin                 = "//linkedin.com/in/you"
  #facebook                 = "//facebook.com/you"
  #googleplus               = "//google.com/you"
  #twitter                  = "//twitter.com/you" 
  #px500                    = "//px500"
  #instagram                = "//instagram.com/you"
  #include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  #googleAnalytics          = "your-google-analytic-id"
    
 
